name: OneLine
version: 1.0
author: SkyZoneMC
api: [3.0.0-ALPHA11]
main: Sky\Oneline\OneLine
description: 'OneLine in Minecraft'
commands:
    ol:
        description: 'Main-Command'
        permission: 'ol.admin'
    leave:
        description: 'Leave the game'
        aliases: [spawn, leave]
    stats:
        description: 'Stats command'
    addtickets:
        description: 'Adds stats-resetters to an player'
        permission: 'ol.tickets'
    hub:
        description: 'Back to hub'
